jobs:
  purge-jsdelivr-cache:
    runs-on: ubuntu-20.04
    steps:
      - uses: gacts/purge-jsdelivr-cache@v1
        with:
          url: |
            https://cdn.jsdelivr.net/gh/NischalChenna/lit-cdn-test@1.2.0/lit-test.js
            https://cdn.jsdelivr.net/gh/NischalChenna/lit-cdn-test@1.3.0/lit-test.js
